language: python
python:
- "3.7"
- "nightly"
install:
- "pip install pytest"
- "pip install pytest_bdd"
- "pip install -r requirements.txt"
script: python -m pytest tests\step_defs\test_retirement_steps.py
